name: E2E Test
on:
  pull_request:
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'
      - '**.md'
      - '**/go.mod'

jobs:
  runner-select:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.runner.outputs.runner }}
    steps:
      - id: runner
        run: echo "runner=[self-hosted, 1ES.Pool=${{ github.event.repository.name }}]" >> $GITHUB_OUTPUT
  acc-tests:
    needs: [runner-select]
    runs-on: ${{ needs.runner-select.outputs.runner }}
    environment:
      name: acctests
    steps:
      - uses: actions/checkout@v3
      - name: e2e test
        run: |
          az login --identity --username $MSI_ID > /dev/null
          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
          docker run --rm -v $(pwd):/src -w /src --network=host -e MSI_ID -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_USE_MSI=true mcr.microsoft.com/azterraform:latest make e2e-test
      - name: version-upgrade test
        run: |
          az login --identity --username $MSI_ID > /dev/null
          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
          docker run --rm -v $(pwd):/src -w /src --network=host -e MSI_ID -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_USE_MSI=true mcr.microsoft.com/azterraform:latest make version-upgrade-test