name: On PR

on:
  pull_request:
    branches:
      - main

jobs:
  terraformsentinalcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUBACCESSTOKEN }}"

      - name: Git config
        run: |
          git config --global user.email "tijo.scaria@gmail.com"
          git config --global user.name "Infrastructure Pipeline"

       - name: Infra Deployment Started
        run: |
          echo "Job started"
          echo "third test"